places_to_see = ['Norway', 'Sweden', 'Finland', 'Denmark', 'Poland']
print(places_to_see)
print(sorted(places_to_see))
print(places_to_see)
print(sorted(places_to_see, reverse=True))
print(places_to_see)
places_to_see.reverse()
print(places_to_see)
places_to_see.reverse()
print(places_to_see)
places_to_see.sort()
print(places_to_see)
places_to_see.sort(reverse=True)
print(places_to_see)
